#!/bin/bash
set -o errexit

echo "*** Development environment with NodeJS and Npm ***"

# Init nodejs environment for 'u01'
/docker-base-init/set-PATH "./node_modules/.bin:/data/nodejs/global/bin"
#/docker-base-init/set-PATH "/opt/node-v${NODE_VERSION}-linux-x64/bin:/opt/node-v${NODE_VERSION}-linux-x64/bin/npm-global/bin"
