#!/bin/bash
# Set "FIXED" environment variables -- export them in /etc/profile

VAR_NAMES=$*
echo ".... Begin to \"FIX\" environment variables: '$VAR_NAMES' ..."
for VAR_NAME in $VAR_NAMES; do
    VAR_VAL="${!VAR_NAME}"

    if [ "" != "$VAR_VAL" ]; then
        echo " .... >>> Add 'FIXED' environment variable: $VAR_NAME"
        echo "export $VAR_NAME=\"$VAR_VAL\"" >> /etc/profile
    else
        echo " .... >>> Skip blank environment variable: $VAR_NAME"
    fi
done
