#!/bin/bash
# Set PS1 variable

echo ".... Set PS1: $1"

PS1_GREEN="\[$(tput bold)$(tput setaf 2)\]"
PS1_RESET="\[$(tput sgr0)\]"
_PS1="${PS1_GREEN}[$1] ${PS1_RESET}\W${PS1_GREEN} > ${PS1_RESET}"

echo "export PS1=\"${_PS1}\"" > /home/u01/.bashrc-docker-PS1
