#!/bin/bash
set -o errexit

/docker-nodejs-init/docker-node-boot

echo "*** Development environment with react-native ***"

# Android SDK environment setup ANDROID_HOME and ANDROID_UPDATE_PROXY
export ANDROID_HOME="/data/android-sdk"
# Calculate Android proxy settings
if [[ ! -z "$http_proxy" ]]; then
    _android_proxy_host=$(python /docker-react-native-init/libs/tool-parse-url.py $http_proxy hostname)
fi

if [[ ! -z "$http_proxy" ]]; then
   _android_proxy_port=$(python /docker-react-native-init/libs/tool-parse-url.py $http_proxy port)
fi

if [[ -z "$http_proxy" ]]; then
    echo " >>> No proxy for Android SDK."
else
	export ANDROID_UPDATE_PROXY="--proxy-host $_android_proxy_host --proxy-port $_android_proxy_port"
    echo " >>> Proxy for Android SDK(\$ANDROID_UPDATE_PROXY): '${ANDROID_UPDATE_PROXY}'"
fi
/docker-base-init/set-fixed-ENVs ANDROID_HOME ANDROID_UPDATE_PROXY
/docker-base-init/set-PATH "$ANDROID_HOME/tools"
/docker-base-init/set-PATH "$ANDROID_HOME/platform-tools"

# Copy Android SDK to /data/android-sdk and update it
if [[ ! -f "/data/.android-sdk-installed" ]]; then
	#Copy installed Android SDK to /data
	cp -Rv /home/u01/android-sdk /data/
	#Update Android SDK
    export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
    echo " >>> Android update sdk with proxy setting: '$ANDROID_UPDATE_PROXY'"
    _packages="platform-tools android-23 build-tools-23.0.1"
    _packages="$_packages extra-android-support extra-android-m2repository sys-img-x86_64-android-23 extra-google-m2repository"
    for _package in $_packages; do
	    echo -e "y" | android update sdk $ANDROID_UPDATE_PROXY --no-https --no-ui --all --filter $_package
    done
    chown -R u01:u01 /data/android-sdk

	#Mark installed
	echo "Created: $(date)" > /data/.android-sdk-installed
fi

# Apply proxy to gradle
mkdir -p /data/home/.gradle
if [[ -f "/data/home/.gradle/gradle.properties" ]]; then
	sed -i '/^systemProp.http.proxyHost=/d' /data/home/.gradle/gradle.properties
	sed -i '/^systemProp.http.proxyPort=/d' /data/home/.gradle/gradle.properties
	sed -i '/^systemProp.https.proxyHost=/d' /data/home/.gradle/gradle.properties
	sed -i '/^systemProp.https.proxyPort=/d' /data/home/.gradle/gradle.properties
fi
if [[ ! -z "$http_proxy" ]]; then
	echo "systemProp.http.proxyHost=$_android_proxy_host" >> /data/home/.gradle/gradle.properties
	echo "systemProp.http.proxyPort=$_android_proxy_port" >> /data/home/.gradle/gradle.properties
	echo "systemProp.https.proxyHost=$_android_proxy_host" >> /data/home/.gradle/gradle.properties
	echo "systemProp.https.proxyPort=$_android_proxy_port" >> /data/home/.gradle/gradle.properties
fi
chown -R u01:u01 /data/home/.gradle

# Apply proxy to android
mkdir -p /data/home/.android
if [[ -f "/data/home/.android/androidtool.cfg" ]]; then
	sed -i '/^http.proxyHost=/d' /data/home/.android/androidtool.cfg
	sed -i '/^http.proxyPort=/d' /data/home/.android/androidtool.cfg
fi
if [[ ! -z "$http_proxy" ]]; then
	echo "http.proxyHost=$_android_proxy_host" >> /data/home/.android/androidtool.cfg
	echo "http.proxyPort=$_android_proxy_port" >> /data/home/.android/androidtool.cfg
fi
chown -R u01:u01 /data/home/.android

#Install react-native at first time
/docker-base-init/set-CMD 'if [[ ! -f "/data/.react-native-installed" ]]; then
    npm install -g yarn react-native-cli
    echo "Created: \$(date)" > /data/.react-native-installed
fi'

echo "========"
