#!/bin/bash
set -o errexit

echo "*** Development environment with code-server ***"

# extensions initialization - child image should install or copy extensions here
if [ ! -d "/data/home/.local/share/code-server/extensions/" ]; then
	# ONLY a BLANK ~/.config/code-server need extensions initialization
	mkdir -p /data/home/.local/share/code-server/extensions
	chown -Rv u01:u01 /data/home/.local/

    /docker-cdr-init/docker-cdr-install-ext.sh
	chown -Rv u01:u01 /data/home/.local/share/code-server/extensions
fi
