#!/bin/bash

# Run docker-compose yml with console
#  1. Start into console(of the main service);
#  2. When exit, all containers should be stoped and removed;
#  3. Requirement:
#    1)The container MUST start into console(for example, run 'bash', or run 'su - u01' ...);
#    2)Use the name of "main" service as docker-compose yml file's name(for example, 'nodejs.yml' MUST has a service 'nodejs');

SHELL_FILE=$(realpath "$0")
SHELL_DIR=$(cd "$(dirname "$SHELL_FILE")"; pwd)

COMPOSE_TYPE="compose-tools"
source "$SHELL_DIR/lib/prepare"

# for "run", create identify name of container
CONTAINER_ID="${YML_FILE}"
CONTAINER_ID="${CONTAINER_ID//\//.}"
CONTAINER_ID="${CONTAINER_ID//\ /_}"
CONTAINER_ID="${CONTAINER_ID//\@/_}"

CMD="docker-compose -f $YML_FILE run --name $COMPOSE_NAME-$CONTAINER_ID --service-ports $COMPOSE_NAME"
#CMD="docker-compose -f $YML_FILE up"
echo "${bldblu}NOTE:${txtrst} Start containers: ${bldgrn}$CMD${txtrst} ..."
$CMD

# remove stopped containers - always just current "main" container itself.
echo "${bldblu}NOTE:${txtrst} Current 'main' container stopped, remove it ..."
docker-compose -f $YML_FILE rm -f
docker-compose -f $YML_FILE down

# if all "main" container instance removed, stop and remove other linked containers
echo "${bldblu}INFO:${txtrst} Check running 'main' containers ..."
docker-compose -f $YML_FILE ps | grep "_${COMPOSE_NAME}_run_"
#docker-compose -f $YML_FILE ps | grep "_${COMPOSE_NAME}_1"
if [ $? -eq 1 ]; then
    echo "${bldblu}NOTE:${txtrst} All 'main' containers stopped, now stop linked containers ..."
    docker-compose -f $YML_FILE stop
    docker-compose -f $YML_FILE rm -f
    docker-compose -f $YML_FILE down
fi

# Try to remove $RUNTIME_DIR (If no data in it)
rmdir -v --ignore-fail-on-non-empty -p "$RUNTIME_DIR"

echo "${bldblu}INFO:${txtrst} ${bldgrn}OK.${txtrst}"
