#!/bin/bash

# Run service defined in docker-compose yml in foreground
#  1. In foreground(Ctrl-C to exit);
#  2. When exit, all containers should be stoped and removed;

SHELL_FILE=$(realpath "$0")
SHELL_DIR=$(cd "$(dirname "$SHELL_FILE")"; pwd)

COMPOSE_TYPE="compose-services"
source "$SHELL_DIR/lib/prepare"

docker-compose -f $YML_FILE up
docker-compose -f $YML_FILE rm -f
